workflows:
  default-workflow:
    name: Зеркало (Python)
    environment:
      vars:
        - GITHUB_TOKEN: encrypted
    scripts:
      - name: Установка зависимостей
        script: pip install -r requirements.txt
      - name: Проверка сборки
        script: echo "Зеркало успешно проверено"
    artifacts:
      - build/**/*
